on:
  release:
    types: [published]

permissions:
  contents: write

name: Release
jobs:
  build:
    name: Build release assets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install build

      - name: Build package
        run: python -m build

      # https://github.com/svenstaro/upload-release-action
      - name: Upload distribution packages to release
        uses: svenstaro/upload-release-action@v2
        with:
          file_glob: true
          file: dist/*
          tag: ${{ github.ref }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}

  hash:
    name: Generate release asset checksums
    runs-on: ubuntu-latest
    steps:
      - name: Generate checksums
        uses: MCJack123/ghaction-generate-release-hashes@v4
        with:
          hash-type: sha256
          file-name: checksums.txt
          get-assets: true

      - name: List checksum file
        run: ls -la

      - name: Upload checksum file to release
        # https://github.com/svenstaro/upload-release-action
        uses: svenstaro/upload-release-action@v2
        with:
          file: checksums.txt
          overwrite: true
          asset_name: checksums_SHA256.txt
          tag: ${{ github.ref }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
