on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

name: Release
jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: python -m pip install --upgrade pip build

      - name: Build package
        run: python -m build

      - name: Generate Asset Hashes
        # https://github.com/jmgilman/actions-generate-checksum
        uses: jmgilman/actions-generate-checksum@v1
        with:
          patterns: dist/*
          method: sha256
          output: checksums.txt

      - name: Create Github Release
        id: github_release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*
            checksums.txt
          fail_on_unmatched_files: true
          token: ${{ secrets.GITHUB_TOKEN }}
